<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>810caf63-7b92-405b-a0e3-d24076c086cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#splash-close-container > svg > path</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#splash-close-container path</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>d02ff4dd-ed8f-4746-8073-f0384b2ffd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 14,1.41 12.59,0 7,5.59 1.41,0 0,1.41 5.59,7 0,12.59 1.41,14 7,8.41 12.59,14 14,12.59 8.41,7 Z</value>
      <webElementGuid>b89e6dbf-bf06-42e9-9466-e62f056ff102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splash-close-container&quot;)/svg[1]/path[1]</value>
      <webElementGuid>c6f3cb62-1d1f-448d-9a70-6ca13a522d6f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
