<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PGANRB300902</name>
   <tag></tag>
   <elementGuidId>39f0c1fb-58fa-4c86-aaac-a6d38bf793a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1 > #station > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//td[@id='station']/a)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PGANRB300902&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48567270-eb15-4ca4-8426-e3e07b3507c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/stations/PGANRB300902</value>
      <webElementGuid>d8f44ea4-48bc-4df1-9de1-1b2ebaa82385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PGANRB300902</value>
      <webElementGuid>77f95a59-9b67-46fb-9a90-d2be0a97513c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/td[@id=&quot;station&quot;]/a[1]</value>
      <webElementGuid>63de5ec7-34b3-4367-8dcc-47df77e150d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//td[@id='station']/a)[2]</value>
      <webElementGuid>649b3d22-0f6f-46ce-ac32-7d54b22d7e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PGANRB300902')]</value>
      <webElementGuid>96dd5906-ddae-47e5-928d-61982f965bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#2'])[1]/following::a[1]</value>
      <webElementGuid>75605b1e-dea8-439d-99c4-dfd4707ae14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[4]/preceding::a[1]</value>
      <webElementGuid>61de5f19-4d75-419e-a08c-6b8b0f23c881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hyderabad'])[1]/preceding::a[1]</value>
      <webElementGuid>f7adfae8-2bc8-466a-a9f9-cb623b7b2c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PGANRB300902']/parent::*</value>
      <webElementGuid>a07e9059-52d8-43b7-a6d6-94b689a9838c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/stations/PGANRB300902')]</value>
      <webElementGuid>1b6e1de0-4a59-409c-ad62-984aaca42a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>0b2d0b3f-1749-432d-94ea-9e0f80fc2fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/stations/PGANRB300902' and (text() = 'PGANRB300902' or . = 'PGANRB300902')]</value>
      <webElementGuid>a58821aa-7b2a-42c1-a3a9-a36a7232b936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
