<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Hyderabad</name>
   <tag></tag>
   <elementGuidId>c84a52d6-ed18-4709-b85a-ff377dee6c00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1 > #city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//td[@id='city'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Hyderabad&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b4f7789e-bbd5-4393-8434-729e56c6fcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>3d8e40fb-5a7e-4ef8-9e49-b16caa99383a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hyderabad</value>
      <webElementGuid>9869fa92-67fe-4f39-87a1-23b9aec9e3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/td[@id=&quot;city&quot;]</value>
      <webElementGuid>2b78656c-640d-4d1e-b5e4-40de3fbdb376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//td[@id='city'])[2]</value>
      <webElementGuid>5b54f473-40f9-44ec-8e57-ba87fa26b289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[4]</value>
      <webElementGuid>5da04512-3386-44c8-884b-13439f3d6645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[4]/following::td[1]</value>
      <webElementGuid>1f7df4b5-5e18-4884-934e-b99a52da5f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PGANRB300902'])[1]/following::td[2]</value>
      <webElementGuid>90621e4e-e1e8-496d-a8da-df263159b4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India, Hyderabad'])[1]/preceding::td[1]</value>
      <webElementGuid>8ece141b-2ef5-498b-990a-7dadd6079230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live'])[2]/preceding::td[2]</value>
      <webElementGuid>927f458e-b0c0-4860-989f-66ab28132538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hyderabad']/parent::*</value>
      <webElementGuid>5ba6e6f2-8669-4890-a276-af722b8e1fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]</value>
      <webElementGuid>6f8656e9-b113-4612-8958-5433e94f7d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'city' and (text() = 'Hyderabad' or . = 'Hyderabad')]</value>
      <webElementGuid>8e19f688-66be-4de7-90eb-ada3d4a39d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
